First game implementation
stempix/snowfall_app pull request #1
Opened 2024-03-25 09:36 UTC by stempix

Выполнение задания по Qt #1. 
Выполнил: Миннулин Эмиль Равилевич

2024-03-25 10:04 UTC, Toxin65 commented on mainwindow.cpp
> +                    this->m_timer->start();
Как страшно. Может уж тогда сделать `singleShot`.

2024-03-25 10:06 UTC, Toxin65 commented on mainwindow.cpp
> +                    QObject::connect(snowflake, &QPushButton::clicked, [snowflake]{snowflake->deleteLater();});
Можно без лямбды, как обычный слот.

2024-03-25 10:06 UTC, Toxin65 commented on mainwindow.cpp
> +                                this,
Получатель неверно указан.

2024-03-25 10:07 UTC, Toxin65 commented on mainwindow.cpp
> +                                    QPoint cursorPos = this->mapFromGlobal(QCursor::pos());
Очень сложно. У кнопки есть метод что-то типа `mouseOver`, показывающий наличие над ней мыши.

2024-03-25 10:11 UTC, Toxin65 commented on mainwindow.cpp
> +                                    int ySnowflake = snowflake->y();
`const`. `const` everywhere!

2024-03-25 10:12 UTC, Toxin65 commented on mainwindow.cpp
> +                                        snowflake_timer->setInterval(snowflake_speed);
А может не надо таймер трогать. По крайней мере я бы не так делал. Лучше величину смещения удвоить.

2024-03-25 10:14 UTC, Toxin65 commented on mainwindow.cpp
> +                                    if (ySnowflake + snowflake->height() >= this->height())
Если `this` захвачен в лямбду, тело лямбды эквивалентно методу класса. `this->` для вызова методов писать не обязательно.

2024-03-25 10:16 UTC, Toxin65 commented on mainwindow.cpp
> +                                    snowflake_timer->start();
Вот это будет ненужно, если не дёргать интервал таймера туда-сюда.

2024-03-25 10:17 UTC, Toxin65 commented on mainwindow.cpp
> +                    int snowflake_speed = QRandomGenerator::global()->bounded(30, 100);
Это не `speed` тогда а `period`.

2024-03-25 10:17 UTC, Toxin65 requested changes
Есть серьёзные ошибки, и не очень...

2024-03-25 11:01 UTC, stempix commented on mainwindow.cpp
> +                    this->m_timer->start();
Вообще убрал.

2024-03-25 11:01 UTC, stempix commented on mainwindow.cpp
> +                    QObject::connect(snowflake, &QPushButton::clicked, [snowflake]{snowflake->deleteLater();});
Исправил.

2024-03-25 11:18 UTC, stempix commented on mainwindow.cpp
> +                                this,
Приступая к исправлению изначально подумал, что правильнее будет указать в качестве получателя снежинку, но потом и вовсе убрал получателя.
Подскажите, пожалуйста, какой же всё-таки верный способ реализации при использовании лямбда-функции в качестве слота ?

2024-03-25 11:18 UTC, stempix commented on mainwindow.cpp
> +                                    QPoint cursorPos = this->mapFromGlobal(QCursor::pos());
Исправлено.

2024-03-25 11:18 UTC, stempix commented on mainwindow.cpp
> +                                    int ySnowflake = snowflake->y();
Убрал.

2024-03-25 11:19 UTC, stempix commented on mainwindow.cpp
> +                                        snowflake_timer->setInterval(snowflake_speed);
Исправлено.

2024-03-25 11:19 UTC, stempix commented on mainwindow.cpp
> +                                    if (ySnowflake + snowflake->height() >= this->height())
Принято, исправил.

2024-03-25 11:19 UTC, stempix commented on mainwindow.cpp
> +                                    snowflake_timer->start();
Согласен, убрал.

2024-03-25 11:19 UTC, stempix commented on mainwindow.cpp
> +                    int snowflake_speed = QRandomGenerator::global()->bounded(30, 100);
Исправлено.

2024-03-25 15:55 UTC, Toxin65 commented on mainwindow.cpp
> +                    snowflake_timer->start();
Лучше всё же его запускать после коннекта. Хотя это не страшно в данном случае.

2024-03-25 15:56 UTC, Toxin65 commented on mainwindow.cpp
> +                                [this, snowflake, snowflake_timer]{
`snowflake_timer` это лишний захват, он не нужен.

2024-03-25 15:57 UTC, Toxin65 approved these changes
В целом всё хорошо.

2024-03-25 15:58 UTC, Toxin65 commented
На каждый коммент отвечать не нужно. Можно просто закоммитить review_fix, а ревьювер сам всё проверит и зарезолвит по очереди замечания. Так удобнее и вам и ревьюверу.

2024-03-26 04:19 UTC, stempix commented on mainwindow.cpp
> +                                [this, snowflake, snowflake_timer]{
Согласен, поправлю.

2024-03-26 04:19 UTC, stempix commented on mainwindow.cpp
> +                    snowflake_timer->start();
А в каких случаях это страшно ?

2024-03-26 06:22 UTC, Toxin65 commented on mainwindow.cpp
> +                    snowflake_timer->start();
Если он щёлкнет до того, как всё будет инициализировано. Это справедливо для многопоточных случаев.

2024-03-26 06:26 UTC, merged